M48
; DRILL file {KiCad 6.0.9+dfsg-1~bpo11+1} date Fri Dec 16 10:54:41 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-16T10:54:41+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T2
X127.6Y-81.2
T3
X123.0Y-69.5
X123.0Y-97.0
X177.0Y-69.5
X177.0Y-97.0
T1
X123.2Y-81.45G85X123.2Y-80.95
G05
T0
M30
